#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Helper to get arguments
const args = process.argv.slice(2);
const outputFlagIndex = args.indexOf('--output');
let customOutputPath = outputFlagIndex !== -1 ? args[outputFlagIndex + 1] : null;

// Search for tokens/ in the current directory
const TOKENS_DIR = path.join(process.cwd(), 'tokens');

// Default output path: assets/styles/tokens.css in the project root
const DEFAULT_OUTPUT = path.join(process.cwd(), 'assets/styles/tokens.css');
const FINAL_OUTPUT = customOutputPath ? path.resolve(process.cwd(), customOutputPath) : DEFAULT_OUTPUT;

/**
 * Recursively flattens a nested object into a flat object with CSS-variable-like keys.
 */
function flattenTokens(obj, prefix = '') {
  let tokens = {};
  for (const key in obj) {
    const value = obj[key];
    const newKey = prefix ? `${prefix}-${key}` : key;
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      Object.assign(tokens, flattenTokens(value, newKey));
    } else {
      tokens[newKey] = value;
    }
  }
  return tokens;
}

function build() {
  console.log('🚀 Zuii — Building tokens...');

  if (!fs.existsSync(TOKENS_DIR)) {
    console.error(`❌ Error: Tokens directory not found at ${TOKENS_DIR}`);
    console.log('Please create a "tokens/" directory with your JSON files.');
    process.exit(1);
  }

  const tokenFiles = fs.readdirSync(TOKENS_DIR).filter(file => file.endsWith('.json'));

  if (tokenFiles.length === 0) {
    console.warn(`⚠️ Warning: No JSON files found in ${TOKENS_DIR}`);
    process.exit(0);
  }

  let mergedTokens = {};

  tokenFiles.forEach(file => {
    const filePath = path.join(TOKENS_DIR, file);
    try {
      const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      Object.assign(mergedTokens, content);
    } catch (e) {
      console.error(`❌ Error parsing ${file}: ${e.message}`);
    }
  });

  const flatTokens = flattenTokens(mergedTokens);

  let cssContent = '/* Generated by Zuii Token CLI */\n';
  cssContent += ':root {\n';
  for (const [key, value] of Object.entries(flatTokens)) {
    cssContent += `  --${key}: ${value};\n`;
  }
  cssContent += '}\n';

  const distDir = path.dirname(FINAL_OUTPUT);
  if (!fs.existsSync(distDir)) {
    fs.mkdirSync(distDir, { recursive: true });
  }

  fs.writeFileSync(FINAL_OUTPUT, cssContent);
  console.log(`✅ Success: Tokens generated at ${FINAL_OUTPUT}`);
}

build();
